services:
  postgres:
    image: postgres:15-alpine
    container_name: zplus-postgres
    environment:
      POSTGRES_DB: zplus_counselling
      POSTGRES_USER: zplus_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zplus_user -d zplus_counselling"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - zplus-network

  mongodb:
    image: mongo:6.0
    container_name: zplus-mongodb
    environment:
      MONGO_INITDB_DATABASE: zplus_content
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - zplus-network

  redis:
    image: redis:7-alpine
    container_name: zplus-redis
    command: redis-server --requirepass secure_password --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - zplus-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: zplus-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - zplus-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zplus-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://postgres:5432/zplus_counselling
      DATABASE_USERNAME: zplus_user
      DATABASE_PASSWORD: secure_password
      MONGODB_URI: mongodb://admin:secure_password@mongodb:27017/zplus_content?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: secure_password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - zplus-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  rabbitmq_data:

networks:
  zplus-network:
    driver: bridge